### ISSUE TITLE
Cascade hangs on instantiating a large number of array elements

### ISSUE THREAD

**Issue by ynaffitgnay** [vmware/cascade#122]
## Overview
When instantiating more than a certain number of elements within a single array, Cascade hangs after the initial declarations in the REPL. This problem occurs whether the instantiations occur inside an initial block or an always block. The instantiated members can be discontiguous, and the error still occurs. When fewer members of an array of the same size are instantiated, the program proceeds as normal.

The memory consumed by Cascade consistently increases by 100 MB every 5 or so seconds while Cascade is hanging. 

A stripped down module that produces this error can be accessed below:
[https://github.com/ynaffitgnay/aos-final/blob/master/bugreports/longarray.v](url)

**Comment by eschkufz** [comment]
Confirmed. 

Depending on the size of the array, cascade goes from returning control immediately to hanging indefinitely when the size increases by one, which makes me think this isn't a memory issue.

**Comment by eschkufz** [comment]
Oh! I know what it is! 

There *is* a small-bit constant floating around in the simulator. I remember thinking to myself at one point: 'we won't ever have a sequential block with more than 256 items in it'. Well... here we are. This'll be a quick fix.
