### ISSUE TITLE
De10 Board hangs on the NW code.

### ISSUE THREAD

**Issue by SolitaryThinker** [vmware/cascade#126]
## Overview

The entire de10 board will hang as soon as Cascade attempts to migrate to hardware after the quartus compilation. CPU through ssh is unresponsive as well, requiring a manual reset of the board.

The copy of the code that causes this behavior can be found here: [https://github.com/SolitaryThinker/needleman-wunsch/tree/bug/de10](https://github.com/SolitaryThinker/needleman-wunsch/tree/bug/de10
)

The fifo folder contains the code using fifo/mem for output.
The original_bug contains code with the fifo output replaced with register which causes de10 to hang.

I'm currently looking through my code again for weird corner cases I might have missed. I'll post updates.

Will

**Comment by SolitaryThinker** [comment]
Seems like simply removing the FIFO output is enough to produce this behavior.

**Comment by eschkufz** [comment]
Closing this ticket as we've deprecated the use of memories and fifo's. The nw benchmarks work with get() and put() now.
