### ISSUE TITLE
Please replace #!/bin/bash with #!/bin/sh

### ISSUE THREAD

**Issue by yurivict** [vmware/cascade#207]
```/bin/bash``` only exists by default on Linux, on other systems it needs to be installed and it has different path. But your scripts work fine with Bourne shell which is available everywhere at ```/bin/sh```.

**Comment by eschkufz** [comment]
I'll start going through these one at a time. We'll close out the easy stuff and then figure out why the regression tests are failing.

**Comment by eschkufz** [comment]
(This one's taking a bit longer than expected --- the scripts in the share/ directory are bash in name only, and mostly posix-compliant. The setup script needs some work.)
