### ISSUE TITLE
Please make the C++ compiler command that appears in installed shell scripts configurable through a cmake variable

### ISSUE THREAD

**Issue by yurivict** [vmware/cascade#208]
```g++``` is from gcc, but there is also a clang compiler, and both gcc and clang executables can have different names.

**Comment by eschkufz** [comment]
Double check that the latest commit to issue-208 still works? I think I removed all instances of g++ from share/ scripts.

**Comment by yurivict** [comment]
```issue-208``` builds, installs and passes regression tests.
