### ISSUE TITLE
Please install includes into include/cascade, not src/cascade

### ISSUE THREAD

**Issue by yurivict** [vmware/cascade#210]

**Comment by eschkufz** [comment]
Works for me. I couldn't figure out what the convention was for headers with inlined source. I read the filesystem hierarchy standard, and it seemed like there was an argument to be made for src/, but it looks like in practice, no one really does this.

**Comment by yurivict** [comment]
Virtually every project installs headers under ```include/```.

**Comment by eschkufz** [comment]
Indeed.
