### ISSUE TITLE
Bison version can be relaxed to 3.0.4

### ISSUE THREAD

**Issue by 3Nigma** [vmware/cascade#215]
[Currently](https://github.com/vmware/cascade/blob/481aae58c362bbb8f9d68ffae9c8b66cad4d9516/CMakeLists.txt#L8), the cmake bison dependency version requirement is set to a minimum of 3.2.0 while the yy templates themselves require a minimum of 3.0.4:
<img width="375" alt="Screenshot 2020-01-04 at 12 43 00" src="https://user-images.githubusercontent.com/210908/71764391-ef980400-2eef-11ea-936d-fe242e29600f.png">

Is there a reason why the version is set higher than necessary? Building the source on Elementary 5.1 fails because of this. It has bison installed only it's the 3.0.4 version. Other distros might also experience this.
<img width="783" alt="Screenshot 2020-01-04 at 12 41 38" src="https://user-images.githubusercontent.com/210908/71764405-34bc3600-2ef0-11ea-8b3c-00e32f6908bc.png">

**Comment by eschkufz** [comment]
No particular reason. Looks like a mistake.
