### ISSUE TITLE
Compiler Error using --march sw

### ISSUE THREAD

**Issue by theishshah** [vmware/cascade#36]
## Overview

- ( ) **Bug report.** 

![cascade_crash](https://user-images.githubusercontent.com/6820886/49193591-6c8f9c00-f334-11e8-93ab-7242b5fc33c5.png)

When following the instructions to use the software fpgs as the backend (from the readme) the entire program crashes and ends.

**Comment by eschkufz** [comment]
Can you say a little bit more about your environment? Is the sw_fpga running? Did it emit any error messages? Do you not have read/write permission on /tmp? The two programs will attempt to communicate with each other over a unix domain socket in that directory.

**Comment by eschkufz** [comment]
Unable to reproduce. Will reopen if new information becomes available.
