### ISSUE TITLE
Documentation for setting up hardware

### ISSUE THREAD

**Issue by SolitaryThinker** [vmware/cascade#72]
The sections for properly setting hardware on a Terasic DE10 Nano SoC is incomplete

I'm trying to set up cascade with a de10, however the instructions linked [here](https://github.com/vmware/cascade/blob/master/README.md#faq) for setting the board for cascade (specifically sshing into the board) is missing. 

Thanks

**Comment by no2chem** [comment]
Hi @SolitaryThinker - We're currently working on updating this with some new instructions, but if you follow the instructions we've created for the 378h lab at UT Austin, that should help you get started:

http://www.cs.utexas.edu/users/rossbach/cs378h/lab/cascade-environment-instructions.html

Of course, let us know if you run into issues or still have questions. Thanks!
